/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Management.Data;
import Management.ManejoArchivo;
import java.awt.Image;
import java.io.File;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author derly
 */
public class Contactos extends javax.swing.JFrame {

    /**
     * Creates new form Contactos
     */
    public Contactos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lContactos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        BTN_Buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF_Usuario = new javax.swing.JTextField();
        TF_Nombre = new javax.swing.JTextField();
        TF_Apellido = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaResultadoBusqueda = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lContactos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lContactosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lContactos);

        jLabel1.setText("Contactos");

        BTN_Buscar.setText("Buscar contacto");
        BTN_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Por usuario:");

        jLabel3.setText("Por nombre:");

        jLabel4.setText("Por apellido:");

        listaResultadoBusqueda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaResultadoBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaResultadoBusquedaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaResultadoBusqueda);

        jLabel5.setText("Resultado de busqueda");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(TF_Usuario)
                            .addComponent(TF_Nombre)
                            .addComponent(TF_Apellido)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BuscarActionPerformed
        var objManejoArchivo = new ManejoArchivo();
        var strError = "";
        File Archivo = new File("C:/MEIA/usuario.txt");
        objManejoArchivo.LimpiarBitacora();
        var cant = 0;
        var usuario = " ";
        var nombre = " ";
        var apellido = " ";
        if (!TF_Usuario.getText().equals("")) {
            usuario = TF_Usuario.getText();
            cant++;
        }
        if (!TF_Nombre.getText().equals("")) {
            nombre = TF_Nombre.getText();
            cant++;
        }
        if (!TF_Apellido.getText().equals("")) {
            apellido = TF_Apellido.getText();
            cant++;
        }
        if (cant != 0) {
            var strBuscar = usuario + "|" + nombre + "|" + apellido;
            var lista = objManejoArchivo.BuscarContacto(Archivo, strBuscar, cant, strError, 9);
            listaResultadoBusqueda.setModel(lista);
        }
    }//GEN-LAST:event_BTN_BuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        File Archivo = new File("C:/MEIA/usuario.txt");
        var objManejoArchivo = new ManejoArchivo();
        var strError = "";
        var dataUser = Data.getData();
        var user = dataUser.getUser();
        var ArchivoUser = objManejoArchivo.BuscarLinea(Archivo, user, strError, 0, 9);
        var split = ArchivoUser.split(Pattern.quote("|"));
        var sistema = new AplicacionMenu();
        sistema.L_Bienvenida.setText("BIENVENIDO:" + split[0]);
        sistema.Dato.setText(split[0]);
        sistema.Dato.setVisible(false);
        if(split[4].equals("1")){
            sistema.L_Rol.setText("Rol: Administrador");
        }else{
            sistema.L_Rol.setText("Rol: Usuario");
        }

        try
        {
            Image img = new ImageIcon(split[8]).getImage();
            Image newImg = img.getScaledInstance(120, 120,  java.awt.Image.SCALE_SMOOTH);
            sistema.L_Image.setIcon(new ImageIcon(newImg));
        } catch(Exception ex){
            strError = ex.getMessage();
        }
        sistema.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lContactosMouseClicked
        var seleccion = lContactos.getSelectedValue();
        if (!seleccion.equals("")) {
            int iRespuesta = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el contacto? ", "¿Eliminar?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (iRespuesta == 0) {
                File Archivo = new File("C:/MEIA/usuario.txt");
                var objManejoArchivo = new ManejoArchivo();
                //Agregar dar de baja a contactos
                listaResultadoBusqueda.clearSelection();
            }
        }
    }//GEN-LAST:event_lContactosMouseClicked

    private void listaResultadoBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaResultadoBusquedaMouseClicked
        var seleccion = listaResultadoBusqueda.getSelectedValue();
        if (!seleccion.equals("")) {
            int iRespuesta = JOptionPane.showConfirmDialog(null, "¿Desea agregar el contacto? ", "¿Agregar?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (iRespuesta == 0) {
                File Archivo = new File("C:/MEIA/usuario.txt");
                var objManejoArchivo = new ManejoArchivo();
                //Agregar insertar en archivo contacto
                //Agregar validacion que no se puede agregar a el mismo
                listaResultadoBusqueda.clearSelection();
            }
        }
    }//GEN-LAST:event_listaResultadoBusquedaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contactos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Buscar;
    private javax.swing.JTextField TF_Apellido;
    private javax.swing.JTextField TF_Nombre;
    private javax.swing.JTextField TF_Usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lContactos;
    private javax.swing.JList<String> listaResultadoBusqueda;
    // End of variables declaration//GEN-END:variables
}
