/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Management.Data;
import Management.ManejoArchivo;
import Management.ABB;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author derly
 */
public class EnvioCorreo extends javax.swing.JFrame {
    ABB ABB = new ABB();
    int Contador = 0;
    
    /**
     * Creates new form EnvioCorreo
     */
    public EnvioCorreo() {
        initComponents();
         try{
                ABB.Cargar();
                }catch(IOException ex) 
                {
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RB_Usuario = new javax.swing.JRadioButton();
        RB_Lista = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        CB_Envios = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        TF_Asunto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_Mensaje = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        TF_Archivo = new javax.swing.JTextField();
        BT_Enviar = new javax.swing.JButton();
        BExit = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enviar:");

        RB_Usuario.setText("Un usuario");
        RB_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB_UsuarioMouseClicked(evt);
            }
        });
        RB_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_UsuarioActionPerformed(evt);
            }
        });

        RB_Lista.setText("Una lista de distribucion");
        RB_Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB_ListaMouseClicked(evt);
            }
        });
        RB_Lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_ListaActionPerformed(evt);
            }
        });

        jLabel2.setText("Escoger receptor:");

        jLabel3.setText("Asunto");

        jLabel4.setText("Mensaje:");

        TA_Mensaje.setColumns(20);
        TA_Mensaje.setRows(5);
        jScrollPane1.setViewportView(TA_Mensaje);

        jLabel5.setText("Archivo:");

        TF_Archivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF_ArchivoMouseClicked(evt);
            }
        });
        TF_Archivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TF_ArchivoKeyPressed(evt);
            }
        });

        BT_Enviar.setText("Enviar");
        BT_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EnviarActionPerformed(evt);
            }
        });

        BExit.setText("Salida");
        BExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CB_Envios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(62, 62, 62)
                        .addComponent(TF_Asunto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RB_Usuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RB_Lista))
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_Archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BExit)))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB_Usuario)
                    .addComponent(RB_Lista))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_Envios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TF_Asunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TF_Archivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BT_Enviar)
                        .addComponent(BExit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RB_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RB_UsuarioMouseClicked

    }// GEN-LAST:event_RB_UsuarioMouseClicked

    private void RB_ListaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RB_ListaMouseClicked

    }// GEN-LAST:event_RB_ListaMouseClicked

    private void TF_ArchivoKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_TF_ArchivoKeyPressed
        evt.consume();
        JFileChooser dialogo = new JFileChooser();
        File ficheroImagen;
        String rutaArchivo;
        int valor = dialogo.showOpenDialog(this);
        if (valor == JFileChooser.APPROVE_OPTION) {
            ficheroImagen = dialogo.getSelectedFile();
            rutaArchivo = ficheroImagen.getPath();
            TF_Archivo.setText(rutaArchivo);
        }
    }// GEN-LAST:event_TF_ArchivoKeyPressed

    private void TF_ArchivoMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TF_ArchivoMouseClicked
        JFileChooser dialogo = new JFileChooser();
        File ficheroImagen;
        String rutaArchivo;
        int valor = dialogo.showOpenDialog(this);
        if (valor == JFileChooser.APPROVE_OPTION) {
            ficheroImagen = dialogo.getSelectedFile();
            rutaArchivo = ficheroImagen.getPath();
            TF_Archivo.setText(rutaArchivo);
        }
    }// GEN-LAST:event_TF_ArchivoMouseClicked

    private void BT_EnviarActionPerformed(java.awt.event.ActionEvent evt){// GEN-FIRST:event_BT_EnviarActionPerformed
        Contador++;                
         var manejoarchivo = new ManejoArchivo();
        var dataUser = Data.getData();
        var user = dataUser.getUser();
        var strError = "";
        var listaEnviar = new DefaultListModel();
        if(RB_Lista.isSelected()){
            var objManejo = new ManejoArchivo();
            var lista = objManejo.lecturaCompleta("Lista_usuario", CB_Envios.getSelectedItem().toString(), user);
            for (int i = 0; i < lista.size(); i++) {
                var splitAux = lista.get(i).split(Pattern.quote("|"));
                listaEnviar.addElement(splitAux[3]);
            }
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date date = new Date();
            for (int i = 0; i < listaEnviar.getSize(); i++) {
                //Insertar en arbol de correo       
                var temp_Adjunto = "null";
               if (!TF_Archivo.getText().equals("")) {
                   temp_Adjunto = TF_Archivo.getText();
               }
                var todosLosRegistros = user + "|" + listaEnviar.get(i) + "|" + dateFormat.format(date) + "|" 
                        + TF_Asunto.getText() + "|" + TA_Mensaje.getText() + "|" + temp_Adjunto  +"|"+ "1";
                String LLave  = user + listaEnviar.get(i) + dateFormat.format(date);
              
                ABB.Insertar(LLave, todosLosRegistros);
                 try {
                    ABB.WriteTree("C:/MEIA/tree.txt");
                    manejoarchivo.ModifyFilesDescUser("tree",9, user, false, strError);
            } catch (IOException ex) {
                //Logger.getLogger(EnvioCorreo.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
           
        }
        else if(RB_Usuario.isSelected()){          
            
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                Date date = new Date();
                //Insertar en arbol de correo
                var temp_Adjunto = "null";
               if (!TF_Archivo.getText().equals("")) {
                   temp_Adjunto = TF_Archivo.getText();
               }
                var todosLosRegistros = user + "|" + CB_Envios.getSelectedItem().toString() + "|" + dateFormat.format(date) + "|"
                        + TF_Asunto.getText() + "|" + TA_Mensaje.getText() + "|" + temp_Adjunto + "|" + "1";
                String LLave  = user + CB_Envios.getSelectedItem().toString()+ dateFormat.format(date);
            
                ABB.Insertar(LLave, todosLosRegistros);   
                 try {
                ABB.WriteTree("C:/MEIA/tree.txt");
                 manejoarchivo.ModifyFilesDescUser("tree",9, user, false, strError);
            } catch (IOException ex) {
                //Logger.getLogger(EnvioCorreo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Error no ha escogido a quien enviar", "ERROR", 1);
        }
    }                                         

    private void RB_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_UsuarioActionPerformed
        if(RB_Usuario.isSelected()){
            RB_Lista.setSelected(false);
            CB_Envios.removeAllItems();
            var dataUser = Data.getData();
            var user = dataUser.getUser();
            var strError = "";
            var objManejoArchivo = new ManejoArchivo();
            File Archivo = new File("C:/MEIA/contactos.txt");
            var lista = objManejoArchivo.LecturaCompleta(Archivo, strError);
            for (int i = 0; i < lista.size(); i++) {
                var splitAux = lista.get(i).split(Pattern.quote("|"));
                if(splitAux[0].equals(user) && splitAux[4].equals("1")){
                   CB_Envios.addItem(splitAux[1]);
                }
            }

            Archivo = new File("C:/MEIA/bitacora_contactos.txt");
            lista = objManejoArchivo.LecturaCompleta(Archivo, strError);
            for (int i = 0; i < lista.size(); i++) {
                var splitAux = lista.get(i).split(Pattern.quote("|"));
                if(splitAux[0].equals(user) && splitAux[4].equals("1")){
                   CB_Envios.addItem(splitAux[1]);
                }
            }
        }
        else{
            CB_Envios.removeAllItems();
        }
    }//GEN-LAST:event_RB_UsuarioActionPerformed

    private void RB_ListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_ListaActionPerformed
        if(RB_Lista.isSelected()){
            RB_Usuario.setSelected(false);
            CB_Envios.removeAllItems();
            var dataUser = Data.getData();
            var user = dataUser.getUser();
            var strError = "";
            var objManejoArchivo = new ManejoArchivo();

            File Archivo = new File("C:/MEIA/lista.txt");
            var lista = objManejoArchivo.LecturaCompleta(Archivo, strError);
            for (int i = 0; i < lista.size(); i++) {
                var splitAux = lista.get(i).split(Pattern.quote("|"));
                if(splitAux[1].equals(user) && splitAux[5].equals("1")){
                   CB_Envios.addItem(splitAux[0]);
                }
            }

            Archivo = new File("C:/MEIA/bitacora_lista.txt");
            lista = objManejoArchivo.LecturaCompleta(Archivo, strError);
            for (int i = 0; i < lista.size(); i++) {
                var splitAux = lista.get(i).split(Pattern.quote("|"));
                if(splitAux[1].equals(user) && splitAux[5].equals("1")){
                   CB_Envios.addItem(splitAux[0]);
                }
            }
        }
        else{
            CB_Envios.removeAllItems();
        }
    }//GEN-LAST:event_RB_ListaActionPerformed

    private void BExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExitActionPerformed
        // TODO add your handling code here:
         File Archivo = new File("C:/MEIA/usuario.txt");
        var objManejoArchivo = new ManejoArchivo();
        var strError = "";
        var dataUser = Data.getData();
        var user = dataUser.getUser();
        var ArchivoUser = objManejoArchivo.BuscarLinea(Archivo, user, strError, 0, 9);
        var split = ArchivoUser.split(Pattern.quote("|"));
        var sistema = new AplicacionMenu();
        sistema.L_Bienvenida.setText("BIENVENIDO:" + split[0]);
        sistema.Dato.setText(split[0]);
        sistema.Dato.setVisible(false);
        if(split[4].equals("1")){
            sistema.L_Rol.setText("Rol: Administrador");
        }else{
            sistema.L_Rol.setText("Rol: Usuario");
        }

        try
        {
            Image img = new ImageIcon(split[8]).getImage();
            Image newImg = img.getScaledInstance(120, 120,  java.awt.Image.SCALE_SMOOTH);
            sistema.L_Image.setIcon(new ImageIcon(newImg));
        } catch(Exception ex){
            strError = ex.getMessage();
        }
        sistema.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnvioCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnvioCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnvioCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnvioCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnvioCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BExit;
    private javax.swing.JButton BT_Enviar;
    private javax.swing.JComboBox<String> CB_Envios;
    private javax.swing.JRadioButton RB_Lista;
    private javax.swing.JRadioButton RB_Usuario;
    private javax.swing.JTextArea TA_Mensaje;
    private javax.swing.JTextField TF_Archivo;
    private javax.swing.JTextField TF_Asunto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
