import java.io.File;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author derly
 */
public class AccesoSistema extends javax.swing.JFrame {

    /**
     * Creates new form AccesoSistema
     */
    public AccesoSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TF_Usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TF_Password = new javax.swing.JTextField();
        BT_Ingresar = new javax.swing.JButton();
        BT_CrearUsuario = new javax.swing.JButton();
        BT_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ingresar usuario:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ingresar contraseña:");

        BT_Ingresar.setText("INGRESAR");
        BT_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_IngresarActionPerformed(evt);
            }
        });

        BT_CrearUsuario.setText("CREAR USUARIO");
        BT_CrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CrearUsuarioActionPerformed(evt);
            }
        });

        BT_Salir.setText("SALIR");
        BT_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(BT_Salir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_Usuario)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT_Ingresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT_CrearUsuario))
                    .addComponent(TF_Password))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TF_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_Ingresar)
                    .addComponent(BT_CrearUsuario)
                    .addComponent(BT_Salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_IngresarActionPerformed
        File Archivo = new File("C:/MEIA/usuario.txt");
        var strError = "";
        ManejoArchivo objManejo = new ManejoArchivo();
        if (objManejo.ExisteCrear(Archivo, strError)){
            if(objManejo.CantidadRegistros(Archivo, strError) > 0){
                if(!TF_Usuario.getText().equals("") && !TF_Password.getText().equals("")){
                    objManejo.RegresarPrincipio(Archivo, strError);
                    var strActual = objManejo.BuscarLinea(Archivo, TF_Usuario.getText(), strError, 0, 9);
                    if(!strActual.equals("")){
                        var split = strActual.split(Pattern.quote("|"));
                        var objUsuario = new ManejoUsuario();
                        if(TF_Password.getText().equals(objUsuario.decrypt(split[3]))){
                            //INGRESO AL SISTEMA
                            JOptionPane.showMessageDialog(null, "Bienvenido", "EXITO", 1);
                            var sistema = new AplicacionMenu();
                            var user = TF_Usuario.getText();
                            sistema.Dato.setText(user);
                            Archivo = new File("C:/MEIA/usuario.txt");
                            var actual = objManejo.BuscarLinea(Archivo, user, strError, 0, 9);
                            split = actual.split(Pattern("|"));
                            try
                            {
                                var image = ImageIO.read(new File(split[8]));
                                JLabel pic = new JLabel(new ImageIcon(image));
                                sistema.P_Imagen.add(pic);
                                sistema.P_Imagen.repaint(); 
                                sistema.L_Bienvenida.setText("BIENVENIDO " + user);
                            } catch(Exception ex){
                                strError = ex.getMessage();
                            }
                            sistema.setVisible(true);
                            this.dispose();
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Contraseña incorrecta", "FALLO", 1);
                        }
                    }
                    else{
                        int iRespuesta = JOptionPane.showConfirmDialog(null, "¿Desea crearlo?", "No existe el usuario ingresado", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (iRespuesta == 0) 
                        {            
                            var fCrearUsuario = new CrearUsuario();
                            fCrearUsuario.Dato.setText("0");
                            fCrearUsuario.Dato.setVisible(false);
                            fCrearUsuario.setVisible(true);
                        }
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Llenar todos los campos", "FALLO", 1);
                }
            }
            else{
                int iRespuesta = JOptionPane.showConfirmDialog(null, "¿Desea crearlo?", "No existe ningun usuario", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (iRespuesta == 0) 
                {
                    var fCrearUsuario = new CrearUsuario();
                    fCrearUsuario.Dato.setText("1");
                    fCrearUsuario.Dato.setVisible(false);
                    fCrearUsuario.setVisible(true);
                }
            }
        }
        
    }//GEN-LAST:event_BT_IngresarActionPerformed

    private void BT_CrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CrearUsuarioActionPerformed
        File Archivo = new File("C:/MEIA/usuario.txt");
        var fCrearUsuario = new CrearUsuario();
        ManejoArchivo objManejo = new ManejoArchivo();
        var strError = "";
        if (objManejo.ExisteCrear(Archivo, strError)){
            if(objManejo.CantidadRegistros(Archivo, strError) > 0){ 
                fCrearUsuario.Dato.setText("0");
                fCrearUsuario.Dato.setVisible(false);
            }
            else{
                fCrearUsuario.Dato.setText("1");
                fCrearUsuario.Dato.setVisible(false);
            }
        } 
        fCrearUsuario.setVisible(true);
    }//GEN-LAST:event_BT_CrearUsuarioActionPerformed

    private void BT_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_SalirActionPerformed
        int iRespuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea salir? ", "¿Salir?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (iRespuesta == 0) 
        {            
            System.exit(0);
        } 
    }//GEN-LAST:event_BT_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesoSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_CrearUsuario;
    private javax.swing.JButton BT_Ingresar;
    private javax.swing.JButton BT_Salir;
    private javax.swing.JTextField TF_Password;
    private javax.swing.JTextField TF_Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private String Pattern(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
